apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-generator-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-generator-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-generator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-generator-role
subjects:
- kind: ServiceAccount
  name: event-generator-serviceaccount
  namespace: default
