apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-controller-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-controller-role-binding
subjects:
- kind: ServiceAccount
  name: job-controller
roleRef:
  kind: Role
  name: job-controller-role
  apiGroup: rbac.authorization.k8s.io
